*VT102 OFF
*VT102 GAPLESS
IF F%=&4201 THEN F$="D.XMASSHR" ELSE IF F%=-1 THEN F$="D.FIREWRK" ELSE INPUT "File? "F$
I%=OPENIN(F$)
A%=0:X%=1:os%=(USR(&FFF4) DIV 256) AND &FF:b_plus%=(os%=2)
IF b_plus% THEN MODE 3 ELSE MODE 131
DIM M% -1
E%=HIMEM-M%-256
DIM D% E%
PRINT CHR$(27);"[?25l";
Q%=-1
IF EXT#I%<=E% THEN PRINT "Loading...";:OSCLI "LOAD "+F$+" "+STR$~D%:O%=0:Q%=EXT#I%:PRINT CHR$(27);"[2J";
REPEAT
IF Q%=-1 THEN C%=BGET #I% ELSE C%=D%?O%
IF O%=-1 THEN S%=EOF#I% ELSE S%=O%=Q%
O%=O%+1
VDU C%
IF F%=&4201 THEN IF O%=&3EA1 THEN O%=&FED:IF Q%=-1 THEN PTR#I%=O%
UNTIL S%
CLOSE #I%
PRINT CHR$(27);"[?25h";
